/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Home;

import Model.User;
import View.Home.HomePanels.ActivityPanel;
import View.Home.HomePanels.AdminDashboardPanel;
import View.Home.HomePanels.GroupsPanel;
import View.Home.HomePanels.MyFilesPanel;
import View.Home.HomePanels.SharedFiles;
import View.Home.HomePanels.UsersPanel;
import View.Resources.CustomFont;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author benjamin
 */
public class AdminHome extends javax.swing.JFrame implements UIMethods {

    static User adminUser;
    
    public AdminHome(User user) {
        initComponents();
        loadFonts();
        applyIcons();
        addPanelsToCard();
        adminUser = user;
        usernamePanel.setText(adminUser.getFirstName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        dashboardPanel = new javax.swing.JPanel();
        dashboardLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        myFilesPanel = new javax.swing.JPanel();
        myFilesLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        sharedFilesPanel = new javax.swing.JPanel();
        sharedFilesLabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        activityPanel = new javax.swing.JPanel();
        activityLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        usersPanel = new javax.swing.JPanel();
        usersLabel = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        groupsPanel = new javax.swing.JPanel();
        groupsLabel = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        profileIcon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        usernamePanel = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1330, 800));
        setMinimumSize(new java.awt.Dimension(1330, 800));
        setPreferredSize(new java.awt.Dimension(1330, 800));

        backgroundPanel.setLayout(new java.awt.BorderLayout());

        menuPanel.setBackground(new java.awt.Color(62, 62, 62));
        menuPanel.setPreferredSize(new java.awt.Dimension(250, 720));
        menuPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(62, 62, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        menuPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel14.setBackground(new java.awt.Color(62, 62, 62));
        jPanel14.setLayout(new java.awt.BorderLayout());

        dashboardPanel.setBackground(new java.awt.Color(62, 62, 62));
        dashboardPanel.setPreferredSize(new java.awt.Dimension(250, 60));
        dashboardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseExited(evt);
            }
        });
        dashboardPanel.setLayout(new java.awt.BorderLayout());

        dashboardLabel.setBackground(new java.awt.Color(255, 255, 255));
        dashboardLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLabel.setText("Dashboard");
        dashboardLabel.setIconTextGap(12);
        dashboardPanel.add(dashboardLabel, java.awt.BorderLayout.CENTER);

        jPanel9.setBackground(new java.awt.Color(62, 62, 62));
        jPanel9.setPreferredSize(new java.awt.Dimension(50, 60));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        dashboardPanel.add(jPanel9, java.awt.BorderLayout.LINE_START);

        jPanel14.add(dashboardPanel, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.BorderLayout());

        myFilesPanel.setBackground(new java.awt.Color(62, 62, 62));
        myFilesPanel.setPreferredSize(new java.awt.Dimension(250, 60));
        myFilesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myFilesPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myFilesPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myFilesPanelMouseExited(evt);
            }
        });
        myFilesPanel.setLayout(new java.awt.BorderLayout());

        myFilesLabel.setBackground(new java.awt.Color(255, 255, 255));
        myFilesLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        myFilesLabel.setForeground(new java.awt.Color(255, 255, 255));
        myFilesLabel.setText("My Files");
        myFilesLabel.setIconTextGap(12);
        myFilesPanel.add(myFilesLabel, java.awt.BorderLayout.CENTER);

        jPanel10.setBackground(new java.awt.Color(62, 62, 62));
        jPanel10.setPreferredSize(new java.awt.Dimension(50, 60));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        myFilesPanel.add(jPanel10, java.awt.BorderLayout.LINE_START);

        jPanel6.add(myFilesPanel, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new java.awt.BorderLayout());

        sharedFilesPanel.setBackground(new java.awt.Color(62, 62, 62));
        sharedFilesPanel.setPreferredSize(new java.awt.Dimension(250, 60));
        sharedFilesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sharedFilesPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sharedFilesPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sharedFilesPanelMouseExited(evt);
            }
        });
        sharedFilesPanel.setLayout(new java.awt.BorderLayout());

        sharedFilesLabel.setBackground(new java.awt.Color(255, 255, 255));
        sharedFilesLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        sharedFilesLabel.setForeground(new java.awt.Color(255, 255, 255));
        sharedFilesLabel.setText("Shared Files");
        sharedFilesLabel.setIconTextGap(12);
        sharedFilesPanel.add(sharedFilesLabel, java.awt.BorderLayout.CENTER);

        jPanel11.setBackground(new java.awt.Color(62, 62, 62));
        jPanel11.setPreferredSize(new java.awt.Dimension(50, 60));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        sharedFilesPanel.add(jPanel11, java.awt.BorderLayout.LINE_START);

        jPanel7.add(sharedFilesPanel, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(62, 62, 62));
        jPanel8.setLayout(new java.awt.BorderLayout());

        activityPanel.setBackground(new java.awt.Color(62, 62, 62));
        activityPanel.setPreferredSize(new java.awt.Dimension(250, 60));
        activityPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activityPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                activityPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                activityPanelMouseExited(evt);
            }
        });
        activityPanel.setLayout(new java.awt.BorderLayout());

        activityLabel.setBackground(new java.awt.Color(255, 255, 255));
        activityLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        activityLabel.setForeground(new java.awt.Color(255, 255, 255));
        activityLabel.setText("Activity");
        activityLabel.setIconTextGap(12);
        activityPanel.add(activityLabel, java.awt.BorderLayout.CENTER);

        jPanel12.setBackground(new java.awt.Color(62, 62, 62));
        jPanel12.setPreferredSize(new java.awt.Dimension(50, 60));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        activityPanel.add(jPanel12, java.awt.BorderLayout.LINE_START);

        jPanel8.add(activityPanel, java.awt.BorderLayout.PAGE_START);

        jPanel13.setLayout(new java.awt.BorderLayout());

        usersPanel.setBackground(new java.awt.Color(62, 62, 62));
        usersPanel.setPreferredSize(new java.awt.Dimension(250, 60));
        usersPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersPanelMouseExited(evt);
            }
        });
        usersPanel.setLayout(new java.awt.BorderLayout());

        usersLabel.setBackground(new java.awt.Color(255, 255, 255));
        usersLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        usersLabel.setForeground(new java.awt.Color(255, 255, 255));
        usersLabel.setText("Users");
        usersLabel.setIconTextGap(12);
        usersPanel.add(usersLabel, java.awt.BorderLayout.CENTER);

        jPanel15.setBackground(new java.awt.Color(62, 62, 62));
        jPanel15.setPreferredSize(new java.awt.Dimension(50, 60));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        usersPanel.add(jPanel15, java.awt.BorderLayout.LINE_START);

        jPanel13.add(usersPanel, java.awt.BorderLayout.PAGE_START);

        jPanel16.setBackground(new java.awt.Color(62, 62, 62));
        jPanel16.setLayout(new java.awt.BorderLayout());

        groupsPanel.setBackground(new java.awt.Color(62, 62, 62));
        groupsPanel.setPreferredSize(new java.awt.Dimension(250, 60));
        groupsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupsPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                groupsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                groupsPanelMouseExited(evt);
            }
        });
        groupsPanel.setLayout(new java.awt.BorderLayout());

        groupsLabel.setBackground(new java.awt.Color(255, 255, 255));
        groupsLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        groupsLabel.setForeground(new java.awt.Color(255, 255, 255));
        groupsLabel.setText("Groups");
        groupsLabel.setIconTextGap(12);
        groupsPanel.add(groupsLabel, java.awt.BorderLayout.CENTER);

        jPanel17.setBackground(new java.awt.Color(62, 62, 62));
        jPanel17.setPreferredSize(new java.awt.Dimension(50, 60));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        groupsPanel.add(jPanel17, java.awt.BorderLayout.LINE_START);

        jPanel16.add(groupsPanel, java.awt.BorderLayout.PAGE_START);

        jPanel13.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel6, java.awt.BorderLayout.CENTER);

        menuPanel.add(jPanel14, java.awt.BorderLayout.CENTER);

        backgroundPanel.add(menuPanel, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 80));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(40, 40, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(180, 80));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new java.awt.BorderLayout());

        profilePanel.setBackground(new java.awt.Color(40, 40, 40));
        profilePanel.setPreferredSize(new java.awt.Dimension(80, 80));
        profilePanel.setLayout(new java.awt.BorderLayout());

        profileIcon.setBackground(new java.awt.Color(255, 255, 255));
        profileIcon.setForeground(new java.awt.Color(242, 242, 242));
        profileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profilePanel.add(profileIcon, java.awt.BorderLayout.CENTER);

        jPanel3.add(profilePanel, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(40, 40, 40));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(40, 40, 40));
        jPanel5.setPreferredSize(new java.awt.Dimension(10, 80));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.LINE_END);

        usernamePanel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        usernamePanel.setForeground(new java.awt.Color(255, 255, 255));
        usernamePanel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        usernamePanel.setText("User");
        jPanel4.add(usernamePanel, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_END);

        backgroundPanel.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        homePanel.setLayout(new java.awt.CardLayout());
        backgroundPanel.add(homePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(backgroundPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        //changeColor(jPanel3, new Color(55, 55, 55));
        changeColor(profilePanel, new Color(55, 55, 55));
        changeColor(jPanel4, new Color(55, 55, 55));
        changeColor(jPanel5, new Color(55, 55, 55));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        changeColor(profilePanel, new Color(40, 40, 40));
        changeColor(jPanel4, new Color(40, 40, 40));
        changeColor(jPanel5, new Color(40, 40, 40));
    }//GEN-LAST:event_jPanel3MouseExited

    private void dashboardPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseEntered
        changeColor(dashboardPanel, new Color(34, 151, 153));
        changeColor(jPanel9, new Color(34, 151, 153));
    }//GEN-LAST:event_dashboardPanelMouseEntered

    private void dashboardPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseExited
        changeColor(dashboardPanel, new Color(62, 62, 62));
        changeColor(jPanel9, new Color(62, 62, 62));
    }//GEN-LAST:event_dashboardPanelMouseExited

    private void dashboardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseClicked
        CardLayout cl = (CardLayout) homePanel.getLayout();
        cl.show(homePanel, "AdminDashboard");
    }//GEN-LAST:event_dashboardPanelMouseClicked

    private void myFilesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myFilesPanelMouseEntered
        changeColor(myFilesPanel, new Color(34, 151, 153));
        changeColor(jPanel10, new Color(34, 151, 153));
    }//GEN-LAST:event_myFilesPanelMouseEntered

    private void myFilesPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myFilesPanelMouseExited
        changeColor(myFilesPanel, new Color(62, 62, 62));
        changeColor(jPanel10, new Color(62, 62, 62));
    }//GEN-LAST:event_myFilesPanelMouseExited

    private void myFilesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myFilesPanelMouseClicked
        CardLayout cl = (CardLayout) homePanel.getLayout();
        cl.show(homePanel, "MyFiles");
    }//GEN-LAST:event_myFilesPanelMouseClicked

    private void sharedFilesPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sharedFilesPanelMouseEntered
        changeColor(sharedFilesPanel, new Color(34, 151, 153));
        changeColor(jPanel11, new Color(34, 151, 153));
    }//GEN-LAST:event_sharedFilesPanelMouseEntered

    private void sharedFilesPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sharedFilesPanelMouseExited
        changeColor(sharedFilesPanel, new Color(62, 62, 62));
        changeColor(jPanel11, new Color(62, 62, 62));
    }//GEN-LAST:event_sharedFilesPanelMouseExited

    private void sharedFilesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sharedFilesPanelMouseClicked
        CardLayout cl = (CardLayout) homePanel.getLayout();
        cl.show(homePanel, "SharedFiles");
    }//GEN-LAST:event_sharedFilesPanelMouseClicked

    private void activityPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activityPanelMouseEntered
        changeColor(activityPanel, new Color(34, 151, 153));
        changeColor(jPanel12, new Color(34, 151, 153));
    }//GEN-LAST:event_activityPanelMouseEntered

    private void activityPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activityPanelMouseExited
        changeColor(activityPanel, new Color(62, 62, 62));
        changeColor(jPanel12, new Color(62, 62, 62));
    }//GEN-LAST:event_activityPanelMouseExited

    private void activityPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activityPanelMouseClicked
        CardLayout cl = (CardLayout) homePanel.getLayout();
        cl.show(homePanel, "ActivityPanel");
    }//GEN-LAST:event_activityPanelMouseClicked

    private void usersPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersPanelMouseClicked
        CardLayout cl = (CardLayout) homePanel.getLayout();
        cl.show(homePanel, "Users");
    }//GEN-LAST:event_usersPanelMouseClicked

    private void usersPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersPanelMouseEntered
        changeColor(usersPanel, new Color(34, 151, 153));
        changeColor(jPanel15, new Color(34, 151, 153));
    }//GEN-LAST:event_usersPanelMouseEntered

    private void usersPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersPanelMouseExited
        changeColor(usersPanel, new Color(62, 62, 62));
        changeColor(jPanel15, new Color(62, 62, 62));
    }//GEN-LAST:event_usersPanelMouseExited

    private void groupsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupsPanelMouseClicked
        CardLayout cl = (CardLayout) homePanel.getLayout();
        cl.show(homePanel, "Groups");
    }//GEN-LAST:event_groupsPanelMouseClicked

    private void groupsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupsPanelMouseEntered
        changeColor(groupsPanel, new Color(34, 151, 153));
        changeColor(jPanel17, new Color(34, 151, 153));
    }//GEN-LAST:event_groupsPanelMouseEntered

    private void groupsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupsPanelMouseExited
        changeColor(groupsPanel, new Color(62, 62, 62));
        changeColor(jPanel17, new Color(62, 62, 62));
    }//GEN-LAST:event_groupsPanelMouseExited
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminHome().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityLabel;
    private javax.swing.JPanel activityPanel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JLabel groupsLabel;
    private javax.swing.JPanel groupsPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel myFilesLabel;
    private javax.swing.JPanel myFilesPanel;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel sharedFilesLabel;
    private javax.swing.JPanel sharedFilesPanel;
    private javax.swing.JLabel usernamePanel;
    private javax.swing.JLabel usersLabel;
    private javax.swing.JPanel usersPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void changeColor(JPanel hover, Color myColor) {
        hover.setBackground(myColor);
    }
    
    private void applyIcons() {
        
        try{
            dashboardLabel.setIcon(
                    new ImageIcon(ImageIO.read(
                            new File("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Icons/dashboard-icon.png"))));
            
            myFilesLabel.setIcon(
                    new ImageIcon(ImageIO.read(
                            new File("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Icons/myfiles-icon.png"))));
            
            sharedFilesLabel.setIcon(
                    new ImageIcon(ImageIO.read(
                            new File("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Icons/shared-icon.png"))));
            
            activityLabel.setIcon(
                    new ImageIcon(ImageIO.read(
                            new File("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Icons/activity-icon.png"))));
            
            groupsLabel.setIcon(
                    new ImageIcon(ImageIO.read(
                            new File("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Icons/groups-icon.png"))));
            
            profileIcon.setIcon(
                    new ImageIcon(ImageIO.read(
                            new File("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Icons/user-icon.png"))));
            
            usersLabel.setIcon(
                    new ImageIcon(ImageIO.read(
                            new File("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Icons/users-icon.png"))));
            
        }catch(IOException e) {
            System.err.println(e.getMessage());
        }
        
        
       
            
   }
    
    private void addPanelsToCard() {
        homePanel.add(new AdminDashboardPanel(), "AdminDashboard");
        homePanel.add(new MyFilesPanel(), "MyFiles");
        homePanel.add(new SharedFiles(), "SharedFiles");
        homePanel.add(new ActivityPanel(), "ActivityPanel");
        homePanel.add(new UsersPanel(), "Users");
        homePanel.add(new GroupsPanel(), "Groups");
    }

    @Override
    public final void loadFonts() {
        float menuFontSize = 16;
        float usernameFontSize = 18;
        
        dashboardLabel.setFont(CustomFont
                .createFont("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Fonts/Inter_18pt-Bold.ttf", menuFontSize));
        
        myFilesLabel.setFont(CustomFont
                .createFont("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Fonts/Inter_18pt-Bold.ttf", menuFontSize));
        
        sharedFilesLabel.setFont(CustomFont
                .createFont("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Fonts/Inter_18pt-Bold.ttf", menuFontSize));
        
        activityLabel.setFont(CustomFont
                .createFont("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Fonts/Inter_18pt-Bold.ttf", menuFontSize));
        
        usernamePanel.setFont(CustomFont
                .createFont("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Fonts/Inter_18pt-Bold.ttf", usernameFontSize));
    }

    @Override
    public void changeFontColor(JLabel text, Color myColor) {
        text.setForeground(myColor);
    }
}
