package View.Home;

import Controller.GroupController;
import Model.GroupModel;
import Model.UserModel;
import View.Resources.CustomFont;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public final class CreateGroupWindow extends javax.swing.JFrame implements UIMethods {
    private String newGroupId;
    private List<UserModel> users;
    private List<String> addedUsernames;
    private static GroupModel newGroup;
    private JLabel userList;
    
    public CreateGroupWindow(List<UserModel> users) {
        this.users = users;
        initComponents();
        userList = new JLabel();
        loadFonts();
        groupIdField.setText(createGroupId().substring(0, 11));
        this.addedUsernames = new ArrayList<>();
        setUserComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        roundPanel2 = new View.Resources.RoundPanel();
        panelHeading = new javax.swing.JLabel();
        groupIdLabel = new javax.swing.JLabel();
        groupIdField = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        roundPanel1 = new View.Resources.RoundPanel();
        roundPanel5 = new View.Resources.RoundPanel();
        sectionHeadingLabel = new javax.swing.JLabel();
        roundPanel3 = new View.Resources.RoundPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        groupNameLabel = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        groupNameTF = new javax.swing.JTextField();
        roundPanel4 = new View.Resources.RoundPanel();
        roundPanel9 = new View.Resources.RoundPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        addUsersLabel = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        userListCombo = new javax.swing.JComboBox<>();
        roundPanel6 = new View.Resources.RoundPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        removeUserBTN = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        addUserBTN = new javax.swing.JButton();
        roundPanel7 = new View.Resources.RoundPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        userDisplayPanel = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        roundPanel12 = new View.Resources.RoundPanel();
        roundPanel13 = new View.Resources.RoundPanel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        roundPanel14 = new View.Resources.RoundPanel();
        jPanel47 = new javax.swing.JPanel();
        roundPanel15 = new View.Resources.RoundPanel();
        cancelBTN = new View.Resources.RoundPanel();
        cancelLabel = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        createBTN = new View.Resources.RoundPanel();
        createLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(541, 560));
        setMinimumSize(new java.awt.Dimension(541, 552));
        setPreferredSize(new java.awt.Dimension(541, 560));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(519, 15));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));
        jPanel2.setPreferredSize(new java.awt.Dimension(15, 350));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));
        jPanel3.setPreferredSize(new java.awt.Dimension(519, 15));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(240, 240, 240));
        jPanel4.setPreferredSize(new java.awt.Dimension(15, 350));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(new java.awt.Color(240, 240, 240));
        jPanel5.setLayout(new java.awt.BorderLayout());

        roundPanel2.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel2.setPreferredSize(new java.awt.Dimension(470, 100));
        roundPanel2.setRoundBottomLeft(10);
        roundPanel2.setRoundBottomRight(10);
        roundPanel2.setRoundTopLeft(10);
        roundPanel2.setRoundTopRight(10);

        panelHeading.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        panelHeading.setText("Create Group");

        groupIdLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        groupIdLabel.setText("Group ID:");

        groupIdField.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        groupIdField.setText("XXXXXX");

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addComponent(groupIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(groupIdField))
                    .addComponent(panelHeading))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelHeading)
                .addGap(5, 5, 5)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupIdLabel)
                    .addComponent(groupIdField))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel5.add(roundPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(240, 240, 240));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(240, 240, 240));
        jPanel7.setPreferredSize(new java.awt.Dimension(552, 20));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(240, 240, 240));
        jPanel8.setLayout(new java.awt.BorderLayout());

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel1.setPreferredSize(new java.awt.Dimension(552, 280));
        roundPanel1.setRoundBottomLeft(10);
        roundPanel1.setRoundBottomRight(10);
        roundPanel1.setRoundTopLeft(10);
        roundPanel1.setRoundTopRight(10);
        roundPanel1.setLayout(new java.awt.BorderLayout());

        roundPanel5.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel5.setPreferredSize(new java.awt.Dimension(100, 60));
        roundPanel5.setRoundTopLeft(10);
        roundPanel5.setRoundTopRight(10);

        sectionHeadingLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        sectionHeadingLabel.setText("Group Details");

        javax.swing.GroupLayout roundPanel5Layout = new javax.swing.GroupLayout(roundPanel5);
        roundPanel5.setLayout(roundPanel5Layout);
        roundPanel5Layout.setHorizontalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(sectionHeadingLabel)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        roundPanel5Layout.setVerticalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(sectionHeadingLabel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        roundPanel1.add(roundPanel5, java.awt.BorderLayout.PAGE_START);

        roundPanel3.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel3.setRoundBottomLeft(10);
        roundPanel3.setRoundBottomRight(10);
        roundPanel3.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(150, 60));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(40, 60));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel12, java.awt.BorderLayout.LINE_START);

        groupNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        groupNameLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        groupNameLabel.setText("Group Name");
        jPanel11.add(groupNameLabel, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel11, java.awt.BorderLayout.LINE_START);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(300, 60));

        groupNameTF.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        groupNameTF.setPreferredSize(new java.awt.Dimension(85, 40));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(groupNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(groupNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel13.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel13, java.awt.BorderLayout.LINE_END);

        roundPanel3.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        roundPanel4.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel4.setRoundBottomLeft(10);
        roundPanel4.setRoundBottomRight(10);
        roundPanel4.setLayout(new java.awt.BorderLayout());

        roundPanel9.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel9.setRoundBottomLeft(10);
        roundPanel9.setRoundBottomRight(10);
        roundPanel9.setLayout(new java.awt.BorderLayout());

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setPreferredSize(new java.awt.Dimension(150, 60));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setPreferredSize(new java.awt.Dimension(40, 60));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel26.add(jPanel27, java.awt.BorderLayout.LINE_START);

        addUsersLabel.setBackground(new java.awt.Color(255, 255, 255));
        addUsersLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        addUsersLabel.setText("Add Users");
        jPanel26.add(addUsersLabel, java.awt.BorderLayout.CENTER);

        jPanel25.add(jPanel26, java.awt.BorderLayout.LINE_START);

        jPanel28.setLayout(new java.awt.BorderLayout());

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setPreferredSize(new java.awt.Dimension(300, 60));

        userListCombo.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        userListCombo.setPreferredSize(new java.awt.Dimension(76, 40));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(userListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(userListCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel28.add(jPanel29, java.awt.BorderLayout.CENTER);

        jPanel25.add(jPanel28, java.awt.BorderLayout.LINE_END);

        roundPanel9.add(jPanel25, java.awt.BorderLayout.PAGE_START);

        roundPanel6.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel6.setRoundBottomLeft(10);
        roundPanel6.setRoundBottomRight(10);
        roundPanel6.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(511, 35));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setPreferredSize(new java.awt.Dimension(45, 40));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel20, java.awt.BorderLayout.LINE_END);

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setPreferredSize(new java.awt.Dimension(40, 60));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel31, java.awt.BorderLayout.LINE_START);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new java.awt.BorderLayout());

        removeUserBTN.setText("Remove");
        removeUserBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeUserBTNMouseClicked(evt);
            }
        });
        jPanel21.add(removeUserBTN, java.awt.BorderLayout.EAST);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new java.awt.BorderLayout());

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setPreferredSize(new java.awt.Dimension(15, 35));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel23, java.awt.BorderLayout.LINE_END);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setLayout(new java.awt.BorderLayout());

        addUserBTN.setText("Add");
        addUserBTN.setMaximumSize(new java.awt.Dimension(85, 24));
        addUserBTN.setMinimumSize(new java.awt.Dimension(85, 24));
        addUserBTN.setPreferredSize(new java.awt.Dimension(85, 24));
        addUserBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserBTNMouseClicked(evt);
            }
        });
        jPanel24.add(addUserBTN, java.awt.BorderLayout.EAST);

        jPanel22.add(jPanel24, java.awt.BorderLayout.CENTER);

        jPanel21.add(jPanel22, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel21, java.awt.BorderLayout.CENTER);

        roundPanel6.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        roundPanel7.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel7.setRoundBottomLeft(10);
        roundPanel7.setRoundBottomRight(10);
        roundPanel7.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setPreferredSize(new java.awt.Dimension(511, 30));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setPreferredSize(new java.awt.Dimension(40, 60));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel30, java.awt.BorderLayout.LINE_START);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setPreferredSize(new java.awt.Dimension(45, 40));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel15, java.awt.BorderLayout.LINE_END);

        userDisplayPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.add(userDisplayPanel, java.awt.BorderLayout.CENTER);

        roundPanel7.add(jPanel16, java.awt.BorderLayout.PAGE_START);

        roundPanel6.add(roundPanel7, java.awt.BorderLayout.CENTER);

        roundPanel9.add(roundPanel6, java.awt.BorderLayout.CENTER);

        roundPanel4.add(roundPanel9, java.awt.BorderLayout.CENTER);

        roundPanel3.add(roundPanel4, java.awt.BorderLayout.CENTER);

        roundPanel1.add(roundPanel3, java.awt.BorderLayout.CENTER);

        jPanel8.add(roundPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel17.setBackground(new java.awt.Color(240, 240, 240));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel18.setBackground(new java.awt.Color(240, 240, 240));
        jPanel18.setPreferredSize(new java.awt.Dimension(511, 20));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel18, java.awt.BorderLayout.PAGE_START);

        jPanel19.setBackground(new java.awt.Color(240, 240, 240));
        jPanel19.setLayout(new java.awt.BorderLayout());

        roundPanel12.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel12.setPreferredSize(new java.awt.Dimension(490, 100));
        roundPanel12.setRoundBottomLeft(10);
        roundPanel12.setRoundBottomRight(10);
        roundPanel12.setRoundTopLeft(10);
        roundPanel12.setRoundTopRight(10);
        roundPanel12.setLayout(new java.awt.BorderLayout());

        roundPanel13.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel13.setPreferredSize(new java.awt.Dimension(30, 100));
        roundPanel13.setRoundBottomRight(10);
        roundPanel13.setRoundTopRight(10);

        javax.swing.GroupLayout roundPanel13Layout = new javax.swing.GroupLayout(roundPanel13);
        roundPanel13.setLayout(roundPanel13Layout);
        roundPanel13Layout.setHorizontalGroup(
            roundPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        roundPanel13Layout.setVerticalGroup(
            roundPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        roundPanel12.add(roundPanel13, java.awt.BorderLayout.LINE_END);

        jPanel45.setBackground(new java.awt.Color(255, 255, 255));
        jPanel45.setLayout(new java.awt.BorderLayout());

        jPanel46.setBackground(new java.awt.Color(240, 240, 240));
        jPanel46.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel46.setVerifyInputWhenFocusTarget(false);
        jPanel46.setLayout(new java.awt.BorderLayout());

        roundPanel14.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel14.setRoundBottomLeft(10);
        roundPanel14.setRoundBottomRight(10);
        roundPanel14.setRoundTopLeft(10);
        roundPanel14.setRoundTopRight(10);

        javax.swing.GroupLayout roundPanel14Layout = new javax.swing.GroupLayout(roundPanel14);
        roundPanel14.setLayout(roundPanel14Layout);
        roundPanel14Layout.setHorizontalGroup(
            roundPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundPanel14Layout.setVerticalGroup(
            roundPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel46.add(roundPanel14, java.awt.BorderLayout.CENTER);

        jPanel45.add(jPanel46, java.awt.BorderLayout.PAGE_END);

        jPanel47.setBackground(new java.awt.Color(240, 240, 240));
        jPanel47.setPreferredSize(new java.awt.Dimension(300, 25));
        jPanel47.setVerifyInputWhenFocusTarget(false);
        jPanel47.setLayout(new java.awt.BorderLayout());

        roundPanel15.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel15.setRoundTopLeft(10);

        javax.swing.GroupLayout roundPanel15Layout = new javax.swing.GroupLayout(roundPanel15);
        roundPanel15.setLayout(roundPanel15Layout);
        roundPanel15Layout.setHorizontalGroup(
            roundPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        roundPanel15Layout.setVerticalGroup(
            roundPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel47.add(roundPanel15, java.awt.BorderLayout.CENTER);

        jPanel45.add(jPanel47, java.awt.BorderLayout.NORTH);

        cancelBTN.setBackground(new java.awt.Color(204, 0, 0));
        cancelBTN.setPreferredSize(new java.awt.Dimension(140, 45));
        cancelBTN.setRoundBottomLeft(30);
        cancelBTN.setRoundBottomRight(30);
        cancelBTN.setRoundTopLeft(30);
        cancelBTN.setRoundTopRight(30);
        cancelBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBTNMouseExited(evt);
            }
        });
        cancelBTN.setLayout(new java.awt.BorderLayout());

        cancelLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        cancelLabel.setForeground(new java.awt.Color(255, 204, 204));
        cancelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelLabel.setText("Cancel");
        cancelBTN.add(cancelLabel, java.awt.BorderLayout.CENTER);

        jPanel45.add(cancelBTN, java.awt.BorderLayout.LINE_END);

        jPanel40.setBackground(new java.awt.Color(255, 255, 255));
        jPanel40.setLayout(new java.awt.BorderLayout());

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setPreferredSize(new java.awt.Dimension(30, 45));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel40.add(jPanel41, java.awt.BorderLayout.LINE_END);

        jPanel44.setBackground(new java.awt.Color(255, 255, 255));
        jPanel44.setLayout(new java.awt.BorderLayout());

        createBTN.setBackground(new java.awt.Color(64, 165, 120));
        createBTN.setPreferredSize(new java.awt.Dimension(140, 45));
        createBTN.setRoundBottomLeft(30);
        createBTN.setRoundBottomRight(30);
        createBTN.setRoundTopLeft(30);
        createBTN.setRoundTopRight(30);
        createBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createBTNMouseExited(evt);
            }
        });
        createBTN.setLayout(new java.awt.BorderLayout());

        createLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        createLabel.setForeground(new java.awt.Color(204, 255, 204));
        createLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createLabel.setText("Create");
        createBTN.add(createLabel, java.awt.BorderLayout.CENTER);

        jPanel44.add(createBTN, java.awt.BorderLayout.LINE_END);

        jPanel40.add(jPanel44, java.awt.BorderLayout.CENTER);

        jPanel45.add(jPanel40, java.awt.BorderLayout.CENTER);

        roundPanel12.add(jPanel45, java.awt.BorderLayout.CENTER);

        jPanel19.add(roundPanel12, java.awt.BorderLayout.PAGE_START);

        jPanel17.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBTNMouseClicked
        int response = JOptionPane.showConfirmDialog(null, setJOptionMessageLabel("Do you want to exit?"), "Warning!", JOptionPane.OK_CANCEL_OPTION);
        if(response == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_cancelBTNMouseClicked

    private void cancelBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBTNMouseEntered
        changeFontColor(cancelLabel, new Color(102,51,0));
        changeColor(cancelBTN, new Color(255,102,102));
    }//GEN-LAST:event_cancelBTNMouseEntered

    private void cancelBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBTNMouseExited
        changeFontColor(cancelLabel, new Color(255,102,102));
        changeColor(cancelBTN, new Color(190, 49, 68));
    }//GEN-LAST:event_cancelBTNMouseExited

    private void createBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBTNMouseClicked
        //check if the form validate returns true
        if(formValidate()) {
            //passing the added users and the new group to the group controller
            if(GroupController.createGroup(createGroupObj())) {
                JOptionPane.showMessageDialog(null, setJOptionMessageLabel("Group created successfully!"), "Success", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(null, setJOptionMessageLabel("Group creation unsuccessful!"), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_createBTNMouseClicked

    private void createBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBTNMouseEntered
        changeFontColor(createLabel, new Color(64, 165, 120));
        changeColor(createBTN, new Color(157, 222, 139));
    }//GEN-LAST:event_createBTNMouseEntered

    private void createBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBTNMouseExited
        changeFontColor(createLabel, new Color(204,255,204));
        changeColor(createBTN, new Color(64,165,120));
    }//GEN-LAST:event_createBTNMouseExited

    private void addUserBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserBTNMouseClicked
        if (userListCombo.getSelectedIndex() != -1) {
            String selectedUser = userListCombo.getSelectedItem().toString();
        
            // Check if the user is already added
            if (addedUsernames.contains(selectedUser)) {
                JOptionPane.showMessageDialog(null, setJOptionMessageLabel("You cannot add the same user multiple times!"), "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                // Add the user to the set and display it on the panel
                addedUsernames.add(selectedUser);
                
                if(userList.getText().isEmpty()) {
                    userList.setText(selectedUser);
                }else {
                    userList.setText(
                            userList.getText() + ", " + selectedUser);
                }
                
                userList.setFont(CustomFont.createFont("/Fonts/SFPRODISPLAYREGULAR.OTF", 15));
                userDisplayPanel.add(userList);
                userDisplayPanel.revalidate();
                userDisplayPanel.repaint();
            }
        }else {
            JOptionPane.showMessageDialog(null, setJOptionMessageLabel("Please select a user from the drop down!"), "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addUserBTNMouseClicked

    private void removeUserBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeUserBTNMouseClicked
        
        if(!addedUsernames.isEmpty()) {
            addedUsernames.clear();
            userList.setText("");
        }else {
            JOptionPane.showMessageDialog(null, setJOptionMessageLabel("No users selected to remove!"), "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_removeUserBTNMouseClicked

    
    @Override
    public void changeColor(JPanel hover, Color myColor) {
        hover.setBackground(myColor);
    }

    @Override
    public void changeFontColor(JLabel text, Color myColor) {
        text.setForeground(myColor);
    }

    @Override
    public void loadFonts() {
        
        sectionHeadingLabel.setFont(CustomFont.sectionHeadingFont);
        panelHeading.setFont(CustomFont.subPanelHeadingFont);
        groupIdLabel.setFont(CustomFont.formLabelFont);
        groupIdField.setFont(CustomFont.formTextFieldFont);
        groupNameLabel.setFont(CustomFont.formLabelFont);
        addUsersLabel.setFont(CustomFont.formLabelFont);
        groupNameTF.setFont(CustomFont.formTextFieldFont);
        userListCombo.setFont(CustomFont.formTextFieldFont);
        createLabel.setFont(CustomFont.formLabelFont);
        cancelLabel.setFont(CustomFont.formLabelFont);
        
    }
    
    private String createGroupId() {
        return this.newGroupId = "group-" + UUID.randomUUID().toString();
    }
    
    private boolean formValidate() {
        //Checks if group name field is not empty
        if(!groupNameTF.getText().isEmpty()) {
            return true;
        }else {
            JOptionPane.showMessageDialog(null, setJOptionMessageLabel("Group name must be defined!"), "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }
    
    private GroupModel createGroupObj() {
        newGroup = new GroupModel(newGroupId ,groupNameTF.getText(), Home.user);
        newGroup.setGroupMembers(getUserObjs());
        
        return newGroup;
    }
    
    private void setUserComboBox() {
        
        for(UserModel user : users) {
            userListCombo.addItem(user.getUsername());
        }
        
        userListCombo.setSelectedIndex(-1);
    }
    
    private List<UserModel> getUserObjs() {
        List<UserModel> addedUserObjs = new ArrayList<>();
        
        for(String username : addedUsernames) {
            for(UserModel user : users) {
                if(username.equals(user.getUsername())) {
                    addedUserObjs.add(user);
                }
            }
        }
        
        return addedUserObjs;
    }
    
    private JLabel setJOptionMessageLabel(String message) {
        JLabel messageLabel = new JLabel(message);
        messageLabel.setFont(CustomFont.formTextFieldFont); 
        
        return messageLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserBTN;
    private javax.swing.JLabel addUsersLabel;
    private View.Resources.RoundPanel cancelBTN;
    private javax.swing.JLabel cancelLabel;
    private View.Resources.RoundPanel createBTN;
    private javax.swing.JLabel createLabel;
    private javax.swing.JLabel groupIdField;
    private javax.swing.JLabel groupIdLabel;
    private javax.swing.JLabel groupNameLabel;
    private javax.swing.JTextField groupNameTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel panelHeading;
    private javax.swing.JButton removeUserBTN;
    private View.Resources.RoundPanel roundPanel1;
    private View.Resources.RoundPanel roundPanel12;
    private View.Resources.RoundPanel roundPanel13;
    private View.Resources.RoundPanel roundPanel14;
    private View.Resources.RoundPanel roundPanel15;
    private View.Resources.RoundPanel roundPanel2;
    private View.Resources.RoundPanel roundPanel3;
    private View.Resources.RoundPanel roundPanel4;
    private View.Resources.RoundPanel roundPanel5;
    private View.Resources.RoundPanel roundPanel6;
    private View.Resources.RoundPanel roundPanel7;
    private View.Resources.RoundPanel roundPanel9;
    private javax.swing.JLabel sectionHeadingLabel;
    private javax.swing.JPanel userDisplayPanel;
    private javax.swing.JComboBox<String> userListCombo;
    // End of variables declaration//GEN-END:variables

    //Gets the respective userId by the username
    private List<String> getSelectedUserIds() {
        List<String> userIds = new ArrayList<>();
        
        
        for(UserModel user : users) {
            for(String username : addedUsernames) {
                if(user.getUsername().equals(username)) {
                    userIds.add(user.getUserId());
                }
            }
        }
        
        return userIds;
    }
    
}
