/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Home;

import View.Home.HomePanels.DashboardPanel;
import View.Home.HomePanels.MyFilesPanel;
import View.Home.HomePanels.SharedFiles;
import View.Resources.CustomFont;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.File;
import java.net.MalformedURLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author benjamin
 */
public class Home extends javax.swing.JFrame implements UIMethods {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        loadFonts();
        applyIcons();
        addPanelsToCard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        dashboardPanel = new javax.swing.JPanel();
        dashboardLable = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        pernalPanel = new javax.swing.JPanel();
        myfilesLable = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        sharedPanel = new javax.swing.JPanel();
        sharedfilesLable = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        activityPanel = new javax.swing.JPanel();
        activityLabel = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        profileIcon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        usernamePanel = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1330, 800));
        setPreferredSize(new java.awt.Dimension(1330, 800));

        backgroundPanel.setLayout(new java.awt.BorderLayout());

        menuPanel.setBackground(new java.awt.Color(62, 62, 62));
        menuPanel.setPreferredSize(new java.awt.Dimension(250, 720));
        menuPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(62, 62, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        menuPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(62, 62, 62));
        jPanel6.setLayout(new java.awt.BorderLayout());

        dashboardPanel.setBackground(new java.awt.Color(62, 62, 62));
        dashboardPanel.setPreferredSize(new java.awt.Dimension(250, 50));
        dashboardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardPanelMouseExited(evt);
            }
        });
        dashboardPanel.setLayout(new java.awt.BorderLayout());

        dashboardLable.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        dashboardLable.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLable.setText("Dashboard");
        dashboardLable.setIconTextGap(10);
        dashboardPanel.add(dashboardLable, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(27, 38, 44));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        dashboardPanel.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel6.add(dashboardPanel, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(62, 62, 62));
        jPanel8.setLayout(new java.awt.BorderLayout());

        pernalPanel.setBackground(new java.awt.Color(62, 62, 62));
        pernalPanel.setPreferredSize(new java.awt.Dimension(250, 50));
        pernalPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pernalPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pernalPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pernalPanelMouseExited(evt);
            }
        });
        pernalPanel.setLayout(new java.awt.BorderLayout());

        myfilesLable.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        myfilesLable.setForeground(new java.awt.Color(255, 255, 255));
        myfilesLable.setText("My Files");
        myfilesLable.setIconTextGap(10);
        pernalPanel.add(myfilesLable, java.awt.BorderLayout.CENTER);

        jPanel9.setBackground(new java.awt.Color(27, 38, 44));
        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pernalPanel.add(jPanel9, java.awt.BorderLayout.LINE_START);

        jPanel8.add(pernalPanel, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(62, 62, 62));
        jPanel10.setLayout(new java.awt.BorderLayout());

        sharedPanel.setBackground(new java.awt.Color(62, 62, 62));
        sharedPanel.setPreferredSize(new java.awt.Dimension(250, 50));
        sharedPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sharedPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sharedPanelMouseExited(evt);
            }
        });
        sharedPanel.setLayout(new java.awt.BorderLayout());

        sharedfilesLable.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        sharedfilesLable.setForeground(new java.awt.Color(255, 255, 255));
        sharedfilesLable.setText("Shared Files");
        sharedfilesLable.setIconTextGap(10);
        sharedfilesLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sharedfilesLableMouseClicked(evt);
            }
        });
        sharedPanel.add(sharedfilesLable, java.awt.BorderLayout.CENTER);

        jPanel11.setBackground(new java.awt.Color(27, 38, 44));
        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        sharedPanel.add(jPanel11, java.awt.BorderLayout.LINE_START);

        jPanel10.add(sharedPanel, java.awt.BorderLayout.PAGE_START);

        jPanel12.setBackground(new java.awt.Color(62, 62, 62));
        jPanel12.setLayout(new java.awt.BorderLayout());

        activityPanel.setBackground(new java.awt.Color(62, 62, 62));
        activityPanel.setPreferredSize(new java.awt.Dimension(250, 50));
        activityPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                activityPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                activityPanelMouseExited(evt);
            }
        });
        activityPanel.setLayout(new java.awt.BorderLayout());

        activityLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        activityLabel.setForeground(new java.awt.Color(255, 255, 255));
        activityLabel.setText("Activity");
        activityLabel.setIconTextGap(10);
        activityPanel.add(activityLabel, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(27, 38, 44));
        jPanel13.setOpaque(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        activityPanel.add(jPanel13, java.awt.BorderLayout.LINE_START);

        jPanel12.add(activityPanel, java.awt.BorderLayout.PAGE_START);

        jPanel10.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        menuPanel.add(jPanel6, java.awt.BorderLayout.CENTER);

        backgroundPanel.add(menuPanel, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 80));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(40, 40, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(180, 80));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new java.awt.BorderLayout());

        profilePanel.setBackground(new java.awt.Color(40, 40, 40));
        profilePanel.setPreferredSize(new java.awt.Dimension(80, 80));
        profilePanel.setLayout(new java.awt.BorderLayout());

        profileIcon.setBackground(new java.awt.Color(255, 255, 255));
        profileIcon.setForeground(new java.awt.Color(242, 242, 242));
        profileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profilePanel.add(profileIcon, java.awt.BorderLayout.CENTER);

        jPanel3.add(profilePanel, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(40, 40, 40));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(40, 40, 40));
        jPanel5.setPreferredSize(new java.awt.Dimension(10, 80));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.LINE_END);

        usernamePanel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        usernamePanel.setForeground(new java.awt.Color(255, 255, 255));
        usernamePanel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        usernamePanel.setText("Admin");
        jPanel4.add(usernamePanel, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_END);

        backgroundPanel.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        homePanel.setLayout(new java.awt.CardLayout());
        backgroundPanel.add(homePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(backgroundPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseEntered
        changeColor(dashboardPanel, new Color(34, 151, 153));
    }//GEN-LAST:event_dashboardPanelMouseEntered

    private void dashboardPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseExited
        changeColor(dashboardPanel, new Color(62, 62, 62));
    }//GEN-LAST:event_dashboardPanelMouseExited

    private void pernalPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pernalPanelMouseEntered
        changeColor(pernalPanel, new Color(34, 151, 153));
    }//GEN-LAST:event_pernalPanelMouseEntered

    private void pernalPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pernalPanelMouseExited
        changeColor(pernalPanel, new Color(62, 62, 62));
    }//GEN-LAST:event_pernalPanelMouseExited

    private void activityPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activityPanelMouseEntered
        changeColor(activityPanel, new Color(34, 151, 153));
    }//GEN-LAST:event_activityPanelMouseEntered

    private void activityPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activityPanelMouseExited
        changeColor(activityPanel, new Color(62, 62, 62));
    }//GEN-LAST:event_activityPanelMouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        //changeColor(jPanel3, new Color(55, 55, 55));
        changeColor(profilePanel, new Color(55, 55, 55));
        changeColor(jPanel4, new Color(55, 55, 55));
        changeColor(jPanel5, new Color(55, 55, 55));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        changeColor(profilePanel, new Color(40, 40, 40));
        changeColor(jPanel4, new Color(40, 40, 40));
        changeColor(jPanel5, new Color(40, 40, 40));
    }//GEN-LAST:event_jPanel3MouseExited

    private void dashboardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPanelMouseClicked
        CardLayout cl = (CardLayout) homePanel.getLayout();
        cl.show(homePanel, "Dashboard");
    }//GEN-LAST:event_dashboardPanelMouseClicked

    private void pernalPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pernalPanelMouseClicked
        CardLayout cl = (CardLayout) homePanel.getLayout();
        cl.show(homePanel, "MyFiles");
    }//GEN-LAST:event_pernalPanelMouseClicked

    private void sharedfilesLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sharedfilesLableMouseClicked
        CardLayout cl = (CardLayout) homePanel.getLayout();
        cl.show(homePanel, "SharedFiles");
    }//GEN-LAST:event_sharedfilesLableMouseClicked

    private void sharedPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sharedPanelMouseEntered
        changeColor(activityPanel, new Color(34, 151, 153));
    }//GEN-LAST:event_sharedPanelMouseEntered

    private void sharedPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sharedPanelMouseExited
        changeColor(activityPanel, new Color(62, 62, 62));
    }//GEN-LAST:event_sharedPanelMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityLabel;
    private javax.swing.JPanel activityPanel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel dashboardLable;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel myfilesLable;
    private javax.swing.JPanel pernalPanel;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel sharedPanel;
    private javax.swing.JLabel sharedfilesLable;
    private javax.swing.JLabel usernamePanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void changeColor(JPanel hover, Color myColor) {
        hover.setBackground(myColor);
    }
    
    private void applyIcons() {

        try{
            dashboardLable.setIcon(new ImageIcon(
                    new File("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Icons/dashboard-icon.png")
                        .toURI()
                        .toURL()));

            myfilesLable.setIcon(new ImageIcon(
                    new File("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Icons/myfiles-icon.png")
                    .toURI()
                    .toURL()));

            sharedfilesLable.setIcon(new ImageIcon(
                    new File("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Icons/shared-icon.png")
                    .toURI()
                    .toURL()));

            activityLabel.setIcon(new ImageIcon(
                    new File("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Icons/activity-icon.png")
                    .toURI()
                    .toURL()));

            profileIcon.setIcon(new ImageIcon(
                    new File("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Icons/user-icon.png")
                    .toURI()
                    .toURL()));

        }catch(MalformedURLException e) {
            System.err.println(e.getMessage());
        }
            
   }
    
    private void addPanelsToCard() {
        homePanel.add(new DashboardPanel(), "Dashboard");
        homePanel.add(new MyFilesPanel(), "MyFiles");
        homePanel.add(new SharedFiles(), "SharedFiles");
    }

    @Override
    public final void loadFonts() {
        float menuFontSize = 16;
        float usernameFontSize = 18;
        
        dashboardLable.setFont(CustomFont
                .createFont("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Fonts/Inter_18pt-Bold.ttf", menuFontSize));
        
        myfilesLable.setFont(CustomFont
                .createFont("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Fonts/Inter_18pt-Bold.ttf", menuFontSize));
        
        sharedfilesLable.setFont(CustomFont
                .createFont("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Fonts/Inter_18pt-Bold.ttf", menuFontSize));
        
        activityLabel.setFont(CustomFont
                .createFont("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Fonts/Inter_18pt-Bold.ttf", menuFontSize));
        
        usernamePanel.setFont(CustomFont
                .createFont("/home/benjamin/file-server-repo/Client/src/main/java/View/Resources/Fonts/Inter_18pt-Bold.ttf", usernameFontSize));
    }

    @Override
    public void changeFontColor(JLabel text, Color myColor) {
        text.setForeground(myColor);
    }
}
