package View.Home.HomePanels;

import Controller.ActivityLoggerController;
import Controller.UserController;
import Models.ActivityLogger;
import Models.GroupModel;
import Models.PasswordHash;
import Models.UserModel;
import View.Home.Home;
import View.Home.UIMethods;
import View.Resources.CustomFont;
import java.awt.Color;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;

/**
 *
 * @author benjamin
 */
public final class AccountDetailsPanel extends javax.swing.JPanel implements UIMethods {
     private UserModel updatedUser;
    /**
     * Creates new form AccountDetailsPanel
     */
    public AccountDetailsPanel() {
        initComponents();
        loadFonts();
        setAccountFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        roundPanel2 = new View.Resources.RoundPanel();
        panelHeading = new javax.swing.JLabel();
        userIdLabel = new javax.swing.JLabel();
        userIdField = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        roundPanel12 = new View.Resources.RoundPanel();
        roundPanel13 = new View.Resources.RoundPanel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        roundPanel14 = new View.Resources.RoundPanel();
        jPanel47 = new javax.swing.JPanel();
        roundPanel15 = new View.Resources.RoundPanel();
        revertBTN = new View.Resources.RoundPanel();
        revertLabel = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        updateBTN = new View.Resources.RoundPanel();
        updateLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        roundPanel1 = new View.Resources.RoundPanel();
        roundPanel3 = new View.Resources.RoundPanel();
        roundPanel5 = new View.Resources.RoundPanel();
        sectionHeadingLabel = new javax.swing.JLabel();
        editFieldsBTN = new javax.swing.JButton();
        roundPanel6 = new View.Resources.RoundPanel();
        roundPanel7 = new View.Resources.RoundPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        usernameTF = new javax.swing.JTextField();
        roundPanel8 = new View.Resources.RoundPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        firstNameTF = new javax.swing.JTextField();
        roundPanel4 = new View.Resources.RoundPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        passwordPF = new javax.swing.JPasswordField();
        roundPanel9 = new View.Resources.RoundPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        roleLabel = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        roleCombo = new javax.swing.JComboBox<>();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        roundPanel10 = new View.Resources.RoundPanel();
        roundPanel11 = new View.Resources.RoundPanel();
        sectionHeadingLabel1 = new javax.swing.JLabel();
        roundPanel16 = new View.Resources.RoundPanel();
        roundPanel17 = new View.Resources.RoundPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        emailTF = new javax.swing.JTextField();
        jPanel48 = new javax.swing.JPanel();
        roundPanel18 = new View.Resources.RoundPanel();
        groupsLabel = new javax.swing.JLabel();
        userGroupNamesLabel = new javax.swing.JLabel();
        roundPanel19 = new View.Resources.RoundPanel();
        jPanel57 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        mobileLabel = new javax.swing.JLabel();
        jPanel60 = new javax.swing.JPanel();
        jPanel61 = new javax.swing.JPanel();
        mobileTF = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setPreferredSize(new java.awt.Dimension(15, 630));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));
        jPanel2.setPreferredSize(new java.awt.Dimension(589, 15));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));
        jPanel3.setPreferredSize(new java.awt.Dimension(15, 630));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(240, 240, 240));
        jPanel4.setPreferredSize(new java.awt.Dimension(589, 15));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        roundPanel2.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel2.setPreferredSize(new java.awt.Dimension(470, 100));
        roundPanel2.setRoundBottomLeft(10);
        roundPanel2.setRoundBottomRight(10);
        roundPanel2.setRoundTopLeft(10);
        roundPanel2.setRoundTopRight(10);

        panelHeading.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        panelHeading.setText("Account Details");

        userIdLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        userIdLabel.setText("User ID:");

        userIdField.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        userIdField.setText("XXXXXX");

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addComponent(userIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userIdField))
                    .addComponent(panelHeading))
                .addContainerGap(889, Short.MAX_VALUE))
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIdLabel)
                    .addComponent(userIdField))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel5.add(roundPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(240, 240, 240));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(240, 240, 240));
        jPanel7.setPreferredSize(new java.awt.Dimension(559, 20));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(240, 240, 240));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel29.setBackground(new java.awt.Color(240, 240, 240));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jPanel31.setBackground(new java.awt.Color(240, 240, 240));
        jPanel31.setLayout(new java.awt.BorderLayout());

        jPanel43.setBackground(new java.awt.Color(240, 240, 240));
        jPanel43.setPreferredSize(new java.awt.Dimension(559, 100));
        jPanel43.setLayout(new java.awt.BorderLayout());

        roundPanel12.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel12.setPreferredSize(new java.awt.Dimension(490, 100));
        roundPanel12.setRoundBottomLeft(10);
        roundPanel12.setRoundBottomRight(10);
        roundPanel12.setRoundTopLeft(10);
        roundPanel12.setRoundTopRight(10);
        roundPanel12.setLayout(new java.awt.BorderLayout());

        roundPanel13.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel13.setPreferredSize(new java.awt.Dimension(30, 100));
        roundPanel13.setRoundBottomRight(10);
        roundPanel13.setRoundTopRight(10);

        javax.swing.GroupLayout roundPanel13Layout = new javax.swing.GroupLayout(roundPanel13);
        roundPanel13.setLayout(roundPanel13Layout);
        roundPanel13Layout.setHorizontalGroup(
            roundPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        roundPanel13Layout.setVerticalGroup(
            roundPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        roundPanel12.add(roundPanel13, java.awt.BorderLayout.LINE_END);

        jPanel45.setBackground(new java.awt.Color(255, 255, 255));
        jPanel45.setLayout(new java.awt.BorderLayout());

        jPanel46.setBackground(new java.awt.Color(240, 240, 240));
        jPanel46.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel46.setVerifyInputWhenFocusTarget(false);
        jPanel46.setLayout(new java.awt.BorderLayout());

        roundPanel14.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel14.setRoundBottomLeft(10);
        roundPanel14.setRoundBottomRight(10);
        roundPanel14.setRoundTopLeft(10);
        roundPanel14.setRoundTopRight(10);

        javax.swing.GroupLayout roundPanel14Layout = new javax.swing.GroupLayout(roundPanel14);
        roundPanel14.setLayout(roundPanel14Layout);
        roundPanel14Layout.setHorizontalGroup(
            roundPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
        );
        roundPanel14Layout.setVerticalGroup(
            roundPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel46.add(roundPanel14, java.awt.BorderLayout.CENTER);

        jPanel45.add(jPanel46, java.awt.BorderLayout.PAGE_END);

        jPanel47.setBackground(new java.awt.Color(240, 240, 240));
        jPanel47.setPreferredSize(new java.awt.Dimension(300, 25));
        jPanel47.setVerifyInputWhenFocusTarget(false);
        jPanel47.setLayout(new java.awt.BorderLayout());

        roundPanel15.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel15.setRoundTopLeft(10);

        javax.swing.GroupLayout roundPanel15Layout = new javax.swing.GroupLayout(roundPanel15);
        roundPanel15.setLayout(roundPanel15Layout);
        roundPanel15Layout.setHorizontalGroup(
            roundPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
        );
        roundPanel15Layout.setVerticalGroup(
            roundPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel47.add(roundPanel15, java.awt.BorderLayout.CENTER);

        jPanel45.add(jPanel47, java.awt.BorderLayout.NORTH);

        revertBTN.setBackground(new java.awt.Color(204, 0, 0));
        revertBTN.setPreferredSize(new java.awt.Dimension(140, 45));
        revertBTN.setRoundBottomLeft(30);
        revertBTN.setRoundBottomRight(30);
        revertBTN.setRoundTopLeft(30);
        revertBTN.setRoundTopRight(30);
        revertBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                revertBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                revertBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                revertBTNMouseExited(evt);
            }
        });
        revertBTN.setLayout(new java.awt.BorderLayout());

        revertLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        revertLabel.setForeground(new java.awt.Color(255, 204, 204));
        revertLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        revertLabel.setText("Revert");
        revertBTN.add(revertLabel, java.awt.BorderLayout.CENTER);

        jPanel45.add(revertBTN, java.awt.BorderLayout.LINE_END);

        jPanel40.setBackground(new java.awt.Color(255, 255, 255));
        jPanel40.setLayout(new java.awt.BorderLayout());

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setPreferredSize(new java.awt.Dimension(30, 45));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel40.add(jPanel41, java.awt.BorderLayout.LINE_END);

        jPanel44.setBackground(new java.awt.Color(255, 255, 255));
        jPanel44.setLayout(new java.awt.BorderLayout());

        updateBTN.setBackground(new java.awt.Color(64, 165, 120));
        updateBTN.setPreferredSize(new java.awt.Dimension(140, 45));
        updateBTN.setRoundBottomLeft(30);
        updateBTN.setRoundBottomRight(30);
        updateBTN.setRoundTopLeft(30);
        updateBTN.setRoundTopRight(30);
        updateBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBTNMouseExited(evt);
            }
        });
        updateBTN.setLayout(new java.awt.BorderLayout());

        updateLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        updateLabel.setForeground(new java.awt.Color(204, 255, 204));
        updateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateLabel.setText("Update");
        updateBTN.add(updateLabel, java.awt.BorderLayout.CENTER);

        jPanel44.add(updateBTN, java.awt.BorderLayout.LINE_END);

        jPanel40.add(jPanel44, java.awt.BorderLayout.CENTER);

        jPanel45.add(jPanel40, java.awt.BorderLayout.CENTER);

        roundPanel12.add(jPanel45, java.awt.BorderLayout.CENTER);

        jPanel43.add(roundPanel12, java.awt.BorderLayout.PAGE_END);

        jPanel9.setBackground(new java.awt.Color(240, 240, 240));
        jPanel9.setLayout(new java.awt.BorderLayout());

        roundPanel1.setBackground(new java.awt.Color(240, 240, 240));
        roundPanel1.setPreferredSize(new java.awt.Dimension(500, 220));
        roundPanel1.setLayout(new java.awt.BorderLayout());

        roundPanel3.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel3.setPreferredSize(new java.awt.Dimension(500, 200));
        roundPanel3.setRoundBottomLeft(10);
        roundPanel3.setRoundBottomRight(10);
        roundPanel3.setRoundTopLeft(10);
        roundPanel3.setRoundTopRight(10);
        roundPanel3.setLayout(new java.awt.BorderLayout());

        roundPanel5.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel5.setPreferredSize(new java.awt.Dimension(100, 60));
        roundPanel5.setRoundTopLeft(10);
        roundPanel5.setRoundTopRight(10);

        sectionHeadingLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        sectionHeadingLabel.setText("User Details");

        editFieldsBTN.setText("Edit");
        editFieldsBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editFieldsBTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout roundPanel5Layout = new javax.swing.GroupLayout(roundPanel5);
        roundPanel5.setLayout(roundPanel5Layout);
        roundPanel5Layout.setHorizontalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(sectionHeadingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 840, Short.MAX_VALUE)
                .addComponent(editFieldsBTN)
                .addGap(17, 17, 17))
        );
        roundPanel5Layout.setVerticalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sectionHeadingLabel)
                    .addComponent(editFieldsBTN))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        roundPanel3.add(roundPanel5, java.awt.BorderLayout.PAGE_START);

        roundPanel6.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel6.setRoundBottomLeft(10);
        roundPanel6.setRoundBottomRight(10);
        roundPanel6.setLayout(new java.awt.BorderLayout());

        roundPanel7.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel7.setPreferredSize(new java.awt.Dimension(500, 240));
        roundPanel7.setRoundBottomLeft(10);
        roundPanel7.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel12, java.awt.BorderLayout.LINE_START);

        usernameLabel.setBackground(new java.awt.Color(255, 255, 255));
        usernameLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        usernameLabel.setText("Username");
        jPanel11.add(usernameLabel, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel11, java.awt.BorderLayout.LINE_START);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(300, 60));

        usernameTF.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        usernameTF.setPreferredSize(new java.awt.Dimension(85, 40));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel13.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel13, java.awt.BorderLayout.LINE_END);

        roundPanel7.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        roundPanel8.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel8.setRoundBottomLeft(10);
        roundPanel8.setLayout(new java.awt.BorderLayout());

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new java.awt.BorderLayout());

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel21.add(jPanel22, java.awt.BorderLayout.LINE_START);

        firstNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        firstNameLabel.setText("First Name");
        jPanel21.add(firstNameLabel, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel21, java.awt.BorderLayout.LINE_START);

        jPanel23.setLayout(new java.awt.BorderLayout());

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setPreferredSize(new java.awt.Dimension(300, 60));

        firstNameTF.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        firstNameTF.setPreferredSize(new java.awt.Dimension(85, 40));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel23.add(jPanel24, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel23, java.awt.BorderLayout.LINE_END);

        roundPanel8.add(jPanel20, java.awt.BorderLayout.PAGE_START);

        roundPanel7.add(roundPanel8, java.awt.BorderLayout.CENTER);

        roundPanel6.add(roundPanel7, java.awt.BorderLayout.LINE_START);

        roundPanel4.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel4.setPreferredSize(new java.awt.Dimension(500, 240));
        roundPanel4.setRoundBottomRight(10);
        roundPanel4.setLayout(new java.awt.BorderLayout());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel17, java.awt.BorderLayout.LINE_START);

        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        passwordLabel.setText("Password");
        jPanel16.add(passwordLabel, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel16, java.awt.BorderLayout.LINE_START);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setPreferredSize(new java.awt.Dimension(300, 60));

        passwordPF.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        passwordPF.setPreferredSize(new java.awt.Dimension(85, 40));
        passwordPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordPFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel18.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel18, java.awt.BorderLayout.LINE_END);

        roundPanel4.add(jPanel15, java.awt.BorderLayout.PAGE_START);

        roundPanel9.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel9.setRoundBottomLeft(10);
        roundPanel9.setRoundBottomRight(10);
        roundPanel9.setLayout(new java.awt.BorderLayout());

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel26.add(jPanel27, java.awt.BorderLayout.LINE_START);

        roleLabel.setBackground(new java.awt.Color(255, 255, 255));
        roleLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        roleLabel.setText("User Role");
        jPanel26.add(roleLabel, java.awt.BorderLayout.CENTER);

        jPanel25.add(jPanel26, java.awt.BorderLayout.LINE_START);

        jPanel28.setLayout(new java.awt.BorderLayout());

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setPreferredSize(new java.awt.Dimension(300, 60));

        roleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Generic" }));
        roleCombo.setPreferredSize(new java.awt.Dimension(76, 30));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(roleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(roleCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel28.add(jPanel30, java.awt.BorderLayout.CENTER);

        jPanel25.add(jPanel28, java.awt.BorderLayout.LINE_END);

        roundPanel9.add(jPanel25, java.awt.BorderLayout.PAGE_START);

        roundPanel4.add(roundPanel9, java.awt.BorderLayout.CENTER);

        roundPanel6.add(roundPanel4, java.awt.BorderLayout.LINE_END);

        roundPanel3.add(roundPanel6, java.awt.BorderLayout.CENTER);

        roundPanel1.add(roundPanel3, java.awt.BorderLayout.CENTER);

        jPanel9.add(roundPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel32.setBackground(new java.awt.Color(240, 240, 240));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jPanel33.setBackground(new java.awt.Color(240, 240, 240));
        jPanel33.setPreferredSize(new java.awt.Dimension(559, 20));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel32.add(jPanel33, java.awt.BorderLayout.PAGE_START);

        jPanel34.setBackground(new java.awt.Color(240, 240, 240));
        jPanel34.setLayout(new java.awt.BorderLayout());

        roundPanel10.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel10.setPreferredSize(new java.awt.Dimension(1023, 205));
        roundPanel10.setRoundBottomLeft(10);
        roundPanel10.setRoundBottomRight(10);
        roundPanel10.setRoundTopLeft(10);
        roundPanel10.setRoundTopRight(10);
        roundPanel10.setLayout(new java.awt.BorderLayout());

        roundPanel11.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel11.setPreferredSize(new java.awt.Dimension(100, 60));
        roundPanel11.setRoundTopLeft(10);
        roundPanel11.setRoundTopRight(10);

        sectionHeadingLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        sectionHeadingLabel1.setText("Contact Details");

        javax.swing.GroupLayout roundPanel11Layout = new javax.swing.GroupLayout(roundPanel11);
        roundPanel11.setLayout(roundPanel11Layout);
        roundPanel11Layout.setHorizontalGroup(
            roundPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(sectionHeadingLabel1)
                .addContainerGap(903, Short.MAX_VALUE))
        );
        roundPanel11Layout.setVerticalGroup(
            roundPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(sectionHeadingLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        roundPanel10.add(roundPanel11, java.awt.BorderLayout.PAGE_START);

        roundPanel16.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel16.setRoundBottomLeft(10);
        roundPanel16.setRoundBottomRight(10);
        roundPanel16.setLayout(new java.awt.BorderLayout());

        roundPanel17.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel17.setPreferredSize(new java.awt.Dimension(500, 240));
        roundPanel17.setRoundBottomLeft(10);
        roundPanel17.setLayout(new java.awt.BorderLayout());

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setLayout(new java.awt.BorderLayout());

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel36.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel36.setLayout(new java.awt.BorderLayout());

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel36.add(jPanel37, java.awt.BorderLayout.LINE_START);

        emailLabel.setBackground(new java.awt.Color(255, 255, 255));
        emailLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        emailLabel.setText("Email");
        jPanel36.add(emailLabel, java.awt.BorderLayout.CENTER);

        jPanel35.add(jPanel36, java.awt.BorderLayout.LINE_START);

        jPanel38.setLayout(new java.awt.BorderLayout());

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setPreferredSize(new java.awt.Dimension(300, 60));

        emailTF.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        emailTF.setPreferredSize(new java.awt.Dimension(85, 40));

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel38.add(jPanel39, java.awt.BorderLayout.CENTER);

        jPanel35.add(jPanel38, java.awt.BorderLayout.LINE_END);

        roundPanel17.add(jPanel35, java.awt.BorderLayout.PAGE_START);

        jPanel48.setBackground(new java.awt.Color(255, 255, 255));
        jPanel48.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        roundPanel17.add(jPanel48, java.awt.BorderLayout.LINE_START);

        roundPanel18.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel18.setPreferredSize(new java.awt.Dimension(800, 80));

        groupsLabel.setBackground(new java.awt.Color(255, 255, 255));
        groupsLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        groupsLabel.setText("Groups:");

        userGroupNamesLabel.setPreferredSize(new java.awt.Dimension(85, 40));

        javax.swing.GroupLayout roundPanel18Layout = new javax.swing.GroupLayout(roundPanel18);
        roundPanel18.setLayout(roundPanel18Layout);
        roundPanel18Layout.setHorizontalGroup(
            roundPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel18Layout.createSequentialGroup()
                .addGroup(roundPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userGroupNamesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        roundPanel18Layout.setVerticalGroup(
            roundPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel18Layout.createSequentialGroup()
                .addComponent(groupsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userGroupNamesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        roundPanel17.add(roundPanel18, java.awt.BorderLayout.CENTER);

        roundPanel16.add(roundPanel17, java.awt.BorderLayout.LINE_START);

        roundPanel19.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel19.setPreferredSize(new java.awt.Dimension(500, 240));
        roundPanel19.setRoundBottomRight(10);
        roundPanel19.setLayout(new java.awt.BorderLayout());

        jPanel57.setBackground(new java.awt.Color(255, 255, 255));
        jPanel57.setLayout(new java.awt.BorderLayout());

        jPanel58.setBackground(new java.awt.Color(255, 255, 255));
        jPanel58.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel58.setLayout(new java.awt.BorderLayout());

        jPanel59.setBackground(new java.awt.Color(255, 255, 255));
        jPanel59.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel59Layout = new javax.swing.GroupLayout(jPanel59);
        jPanel59.setLayout(jPanel59Layout);
        jPanel59Layout.setHorizontalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel59Layout.setVerticalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel58.add(jPanel59, java.awt.BorderLayout.LINE_START);

        mobileLabel.setBackground(new java.awt.Color(255, 255, 255));
        mobileLabel.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        mobileLabel.setText("Mobile");
        jPanel58.add(mobileLabel, java.awt.BorderLayout.CENTER);

        jPanel57.add(jPanel58, java.awt.BorderLayout.LINE_START);

        jPanel60.setLayout(new java.awt.BorderLayout());

        jPanel61.setBackground(new java.awt.Color(255, 255, 255));
        jPanel61.setPreferredSize(new java.awt.Dimension(300, 60));

        mobileTF.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        mobileTF.setPreferredSize(new java.awt.Dimension(85, 40));

        javax.swing.GroupLayout jPanel61Layout = new javax.swing.GroupLayout(jPanel61);
        jPanel61.setLayout(jPanel61Layout);
        jPanel61Layout.setHorizontalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel61Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(mobileTF, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel61Layout.setVerticalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel61Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(mobileTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel60.add(jPanel61, java.awt.BorderLayout.CENTER);

        jPanel57.add(jPanel60, java.awt.BorderLayout.LINE_END);

        roundPanel19.add(jPanel57, java.awt.BorderLayout.PAGE_START);

        roundPanel16.add(roundPanel19, java.awt.BorderLayout.LINE_END);

        roundPanel10.add(roundPanel16, java.awt.BorderLayout.CENTER);

        jPanel34.add(roundPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel32.add(jPanel34, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel32, java.awt.BorderLayout.CENTER);

        jPanel43.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel31.add(jPanel43, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel31, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel29, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void updateBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBTNMouseExited
        changeFontColor(updateLabel, new Color(204,255,204));
        changeColor(updateBTN, new Color(64,165,120));
    }//GEN-LAST:event_updateBTNMouseExited

    private void updateBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBTNMouseEntered
        changeFontColor(updateLabel, new Color(64, 165, 120));
        changeColor(updateBTN, new Color(157, 222, 139));
    }//GEN-LAST:event_updateBTNMouseEntered

    private void updateBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBTNMouseClicked
         try {
             updateUserObj();
             if(UserController.updateUser(updatedUser)) {
                 JOptionPane.showMessageDialog(null, "Account updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                 ActivityLoggerController.logActivity(
                    new ActivityLogger(Home.user.getUsername(), null, "Updated the account details", new Date().toString()));
             } else {
                 JOptionPane.showMessageDialog(null, "Account updation unsuccessful!", "Error", JOptionPane.ERROR_MESSAGE);
                 ActivityLoggerController.logActivity(
                    new ActivityLogger(Home.user.getUsername(), null, "Account updation unsuccessful", new Date().toString()));
             }
         } catch (Exception ex) {
             System.err.println(ex.getMessage());
         }
    }//GEN-LAST:event_updateBTNMouseClicked

    private void revertBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revertBTNMouseExited
        changeFontColor(revertLabel, new Color(255,102,102));
        changeColor(revertBTN, new Color(190, 49, 68));
    }//GEN-LAST:event_revertBTNMouseExited

    private void revertBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revertBTNMouseEntered
        changeFontColor(revertLabel, new Color(102,51,0));
        changeColor(revertBTN, new Color(255,102,102));
    }//GEN-LAST:event_revertBTNMouseEntered

    private void revertBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revertBTNMouseClicked
        int response = JOptionPane.showConfirmDialog(null, "Do want to revert the changes?", "Warning!", JOptionPane.OK_CANCEL_OPTION);
        if(response == 0) {
            setAccountFields();
        }
    }//GEN-LAST:event_revertBTNMouseClicked

    private void editFieldsBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editFieldsBTNMouseClicked
        usernameTF.setEnabled(true);
        passwordPF.setEnabled(true);
        firstNameTF.setEnabled(true);
        mobileTF.setEnabled(true);
        roleCombo.setEnabled(true);
        emailTF.setEnabled(true);
    }//GEN-LAST:event_editFieldsBTNMouseClicked

    private void passwordPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordPFMouseClicked
        JPasswordField confirmPassword = new JPasswordField();
        int option = JOptionPane.showConfirmDialog(null, confirmPassword, "Confirm the exsiting password", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        if (option == JOptionPane.OK_OPTION) {
            // Get the entered password as a string
            String enteredPassword = new String(confirmPassword.getPassword());
            //Entered password should be hashed
            //String hashedPassowrd = PasswordHash.hash(enteredPassword);
            //Check if the user entered password is matching with the user account password
            if(Home.user.getPassword().equals(enteredPassword)) {
               passwordPF.setText(null); 
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect password!", "Warning", JOptionPane.WARNING_MESSAGE);
                ActivityLoggerController.logActivity(
                    new ActivityLogger(Home.user.getUsername(), null, "Unautharized password change attempt", new Date().toString()));
                setAccountFields();
            }
                
        } else {
            setAccountFields();
        }
    }//GEN-LAST:event_passwordPFMouseClicked

    private void updateUserObj() throws Exception {
        updatedUser.setUsername(usernameTF.getText());
        updatedUser.setPassword(PasswordHash.hash(new String(passwordPF.getPassword())));
        updatedUser.setFirstName(firstNameTF.getText());
        updatedUser.setMobile(mobileTF.getText());
        updatedUser.setRole(roleCombo.getSelectedItem().toString());
        updatedUser.setEmail(emailTF.getText());
    }
    
    
    @Override
    public void changeColor(JPanel hover, Color myColor) {
        hover.setBackground(myColor);
    }

    @Override
    public void changeFontColor(JLabel text, Color myColor) {
        text.setForeground(myColor);
    }

    @Override
    public void loadFonts() {
        sectionHeadingLabel.setFont(CustomFont.sectionHeadingFont);
        sectionHeadingLabel1.setFont(CustomFont.sectionHeadingFont);
        panelHeading.setFont(CustomFont.subPanelHeadingFont);
        updateLabel.setFont(CustomFont.formLabelFont);
        revertLabel.setFont(CustomFont.formLabelFont);
        userIdLabel.setFont(CustomFont.formLabelFont);
        usernameLabel.setFont(CustomFont.formLabelFont);
        passwordLabel.setFont(CustomFont.formLabelFont);
        firstNameLabel.setFont(CustomFont.formLabelFont);
        mobileLabel.setFont(CustomFont.formLabelFont);
        roleLabel.setFont(CustomFont.formLabelFont);
        emailLabel.setFont(CustomFont.formLabelFont);
        groupsLabel.setFont(CustomFont.formLabelFont);
        usernameTF.setFont(CustomFont.formTextFieldFont);
        usernameTF.setFont(CustomFont.formTextFieldFont);
        passwordPF.setFont(CustomFont.formTextFieldFont);
        firstNameTF.setFont(CustomFont.formTextFieldFont);
        mobileTF.setFont(CustomFont.formTextFieldFont);
        roleCombo.setFont(CustomFont.formTextFieldFont);
        emailTF.setFont(CustomFont.formTextFieldFont);
        userGroupNamesLabel.setFont(CustomFont.formTextFieldFont);
    }
    
    private void setAccountFields() {
        //Textfields are disabled by default
        usernameTF.setEnabled(false);
        passwordPF.setEnabled(false);
        firstNameTF.setEnabled(false);
        mobileTF.setEnabled(false);
        roleCombo.setEnabled(false);
        emailTF.setEnabled(false);
        
        
        //Setting textfields as per user details
        userIdField.setText(Home.user.getUserId());
        usernameTF.setText(Home.user.getUsername());
        passwordPF.setText(Home.user.getPassword());
        firstNameTF.setText(Home.user.getFirstName());
        mobileTF.setText(Home.user.getMobile());
        roleCombo.setSelectedItem(Home.user.getRole());
        emailTF.setText(Home.user.getEmail());
        userGroupNamesLabel.setText(getGroupNames());
        
    }
    
    private String getGroupNames() {
        List<GroupModel> groups = Home.user.getGroups();
        String groupNames = null;
        
        for(GroupModel group : groups) {
            if(groupNames == null) {
                groupNames = group.getGroupName() + ", ";
            } else {
                groupNames += group.getGroupName() + ", ";
            }
            
        }
        return groupNames;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editFieldsBTN;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JLabel groupsLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobileTF;
    private javax.swing.JLabel panelHeading;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordPF;
    private View.Resources.RoundPanel revertBTN;
    private javax.swing.JLabel revertLabel;
    private javax.swing.JComboBox<String> roleCombo;
    private javax.swing.JLabel roleLabel;
    private View.Resources.RoundPanel roundPanel1;
    private View.Resources.RoundPanel roundPanel10;
    private View.Resources.RoundPanel roundPanel11;
    private View.Resources.RoundPanel roundPanel12;
    private View.Resources.RoundPanel roundPanel13;
    private View.Resources.RoundPanel roundPanel14;
    private View.Resources.RoundPanel roundPanel15;
    private View.Resources.RoundPanel roundPanel16;
    private View.Resources.RoundPanel roundPanel17;
    private View.Resources.RoundPanel roundPanel18;
    private View.Resources.RoundPanel roundPanel19;
    private View.Resources.RoundPanel roundPanel2;
    private View.Resources.RoundPanel roundPanel3;
    private View.Resources.RoundPanel roundPanel4;
    private View.Resources.RoundPanel roundPanel5;
    private View.Resources.RoundPanel roundPanel6;
    private View.Resources.RoundPanel roundPanel7;
    private View.Resources.RoundPanel roundPanel8;
    private View.Resources.RoundPanel roundPanel9;
    private javax.swing.JLabel sectionHeadingLabel;
    private javax.swing.JLabel sectionHeadingLabel1;
    private View.Resources.RoundPanel updateBTN;
    private javax.swing.JLabel updateLabel;
    private javax.swing.JLabel userGroupNamesLabel;
    private javax.swing.JLabel userIdField;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables

}
